### ISSUE TITLE
How many packets in one frame?

### ISSUE THREAD

**Issue by licj15** [HesaiTechnology/HesaiLidarSDK#5]
When I use pandarview, I noticed that there are more than one UDP packets in one frame. But I don't know the accurate number. we know one packet has 10 blocks *40 units = 400 points for Panda40P. So I guess maybe we use m packets in each frame and move n packets to update. If thing do like this, what's the m and n?

**Comment by trickyMan** [comment]
Actually, The number of the packets in a frame is not constant. Because the speed of engine is not constant, eg. the speed is 600RPM , the real engine speed maybe is 602/598 (+/- 2RPM).
In general speaking, in single return mode, there are 1800 packets/s. and 3600 packets/s for dual return mode. so , [Pandar40P/40 Dual Return Model]there are 180 packets a frame in 600RPM(10HZ) , and 360 packets in 600RPM(10HZ)

I suggest that you should get a frame by checking the Azimuth in a packet. if the Azimuth changed from 359.999 degree to 0 degree.

**Comment by licj15** [comment]
Thanks a lot!
I got it. So in PandaView,  there is no overlap packet between different frames? That's to say, we just count packets until we meet a packet whose Azimuth changed from 359.999 degree to 0 degree, then we put them in one frame, and we count from the packet after it?

**Comment by trickyMan** [comment]
Yes, Caution: The "Azimuth jump" maybe in the middle of the packet. there are 10 blocks in a packet , That means there are 10 Azimuth in a packet.

**Comment by licj15** [comment]
Thank you for your tips. I got it. It helps a lot to process a .pcap file into numpy.array to use Open3D and tensorflow in Python.
